services:
  - type: web
    name: youtube-qa-app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: AUTH_USERNAME
        sync: false
      - key: AUTH_PASSWORD
        sync: false
    runtime: python
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1